name: Deploy to Vercel

on:
  push:
    branches:
      - feature/preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Vercel Action
        id: vercel_deploy
        run: |
          npm install -g vercel
          DEPLOYMENT_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm)
          echo "DEPLOYMENT_URL=${DEPLOYMENT_URL}" >> $GITHUB_ENV

      - name: Add PR comment
        uses: actions/github-script@v6
        with:
          script: |
            const deploymentUrl = process.env.DEPLOYMENT_URL;
            const { context, github } = require('@actions/github');
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `feature/preview`
            });

            if (pr.data.length > 0) {
              const prNumber = pr.data[0].number;
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `This PR contains the Vercel Preview URL: ${deploymentUrl}`
              });
            }
