name: Deploy to Vercel

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Check Semgrep status
        id: check_semgrep
        run: |
          if [ -f semgrep-fail.txt ]; then
            echo "Semgrep failed. Deployment aborted."
            exit 1
          fi

      - name: Deploy to Vercel
        id: deploy
        if: steps.check_semgrep.conclusion == 'success'
        run: |
          vercel link --yes --project ${{ secrets.VERCEL_PROJECT_ID }} --scope ${{ secrets.VERCEL_ORG_ID }} --token ${{ secrets.VERCEL_TOKEN }}
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "PREVIEW_URL=$(vercel --cwd ./ --token ${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
          else
            vercel --cwd ./ --prod --token ${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Add PR comment
        if: github.event_name == 'pull_request' && steps.deploy.conclusion == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = '${{ steps.deploy.outputs.PREVIEW_URL }}';
            const prodUrl = '${{ steps.deploy.outputs.PROD_URL }}';
            const body = prodUrl
              ? `Preview build URL: ${previewUrl}\nProduction build URL: ${prodUrl}\ncbon`
              : `Preview build URL: ${previewUrl}\nc bon`;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
