name: Deploy and Create PR with Vercel Preview URL

on:
  push:
    branches:
      - feature/preview

jobs:
  deploy-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        id: vercel_deploy
        run: |
          DEPLOYMENT_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm)
          echo "DEPLOYMENT_URL=${DEPLOYMENT_URL}" >> $GITHUB_ENV
          echo "::set-output name=vercel_url::${DEPLOYMENT_URL}"

      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: "Add Vercel Preview URL"
          title: "Vercel Preview URL"
          body: "This PR contains the Vercel Preview URL: ${{ steps.vercel_deploy.outputs.vercel_url }}"
          branch: "vercel-preview-url"
          base: "main"

      - name: Comment PR with Preview URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: context.repo.owner + ':vercel-preview-url'
            });
            if (pr.data.length > 0) {
              await github.rest.issues.createComment({
                issue_number: pr.data[0].number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Preview URL: ${{ steps.vercel_deploy.outputs.vercel_url }}`
              });
            }
