name: Deploy to Vercel

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Check Semgrep status
        id: semgrep_status
        run: |
          if [ -f .failed_semgrep ]; then
            echo "Semgrep failed. Deployment aborted."
            exit 1
          fi

      - name: Deploy to Vercel
        if: success()
        id: deploy
        run: |
          vercel link --yes --project ${{ secrets.VERCEL_PROJECT_ID }} --scope ${{ secrets.VERCEL_ORG_ID }} --token ${{ secrets.VERCEL_TOKEN }}
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "PREVIEW_URL=$(vercel --cwd ./ --token ${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
          else
            vercel --cwd ./ --prod --token ${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Add PR comment for success
        if: github.event_name == 'pull_request' && steps.semgrep_status.outcome == 'success'
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = '${{ steps.deploy.outputs.PREVIEW_URL }}';
            const prodUrl = '${{ steps.deploy.outputs.PROD_URL }}';
            const body = prodUrl
              ? `Preview build URL: ${previewUrl}\nProduction build URL: ${prodUrl}\nc bon`
              : `Preview build URL: ${previewUrl}\nc bon`;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

      - name: Read Semgrep error and comment
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const sarif = fs.readFileSync('semgrep.sarif', 'utf8');
            const body = `Erreur Semgrep détectée:\n\n\`\`\`json\n${sarif}\n\`\`\``;
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
