name: Semgrep CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep
      id: semgrep
      run: |
        semgrep --config .semgrep.yml --error --metrics=off --output semgrep.sarif --json
      continue-on-error: true

    - name: Archive Semgrep results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-results
        path: semgrep.sarif

    - name: Set Semgrep status
      if: failure()
      run: echo "Semgrep failed" > .failed_semgrep
