name: Semgrep CI

on:
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: |
        python -m pip install --upgrade pip
        pip install semgrep

    - name: Run Semgrep
      id: run_semgrep
      run: semgrep --config .semgrep.yml --error --metrics=off

    - name: Archive Semgrep results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-results
        path: semgrep.sarif

    - name: Display Semgrep results
      if: failure()
      run: cat semgrep.sarif

    - name: Comment on PR if XSS error
      if: failure()
      uses: actions/github-script@v5
      with:
        script: |
          const message = '### Semgrep Analysis Found Issues\n\nUne erreur XSS a été détectée dans votre code. Veuillez corriger cela avant de fusionner.';
          await github.rest.issues.createComment({
            issue_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
